[platformio]
default_envs = esp32_motor_bringup

[env:esp32_motor_bringup]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    askuric/Simple FOC@2.4.0
build_flags =
    -DTRIWHIRL_MOTOR_BRINGUP=1
    -Wall
    -Wextra
