#include "runtime_simplefoc_sensor_commissioning.hpp"

#if defined(TRIWHIRL_ROUTE_B_SENSOR_COMMISSIONING) && \
    defined(TRIWHIRL_ROUTE_B_SIMPLEFOC_BACKEND)

#include <Arduino.h>

#if defined(TRIWHIRL_ROUTE_B_SENSOR_COMMISSIONING_BT)
#include "esp32-hal-alloc-bt-classic-mem.h"
#include "esp32-hal-bt.h"
#include "esp_bt.h"
#include "esp_bt_main.h"
#include "esp_gap_bt_api.h"
#include "esp_spp_api.h"
#if !defined(CONFIG_BT_ENABLED) || !defined(CONFIG_BLUEDROID_ENABLED) || \
    !defined(CONFIG_BT_CLASSIC_ENABLED) || !defined(CONFIG_BT_SPP_ENABLED)
#error "Bluetooth sensor commissioning requires Bluedroid + Classic BT + SPP"
#endif
#endif

#include <algorithm>
#include <atomic>
#include <cinttypes>
#include <cstdio>
#include <cstdint>
#include <limits>

#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/queue.h"
#include "freertos/task.h"
#include "triwhirl/board.hpp"
#include "triwhirl/simplefoc_sensor_path.hpp"

namespace triwhirl::runtime {
namespace {

// Existing physical AS5600 bus configuration. This is not a motor-control or
// fuzzy tuning parameter.
constexpr std::uint32_t kSensorBusHz = 400000U;
constexpr std::uint32_t kServicePeriodMs = 1U;
constexpr std::uint32_t kTelemetryPeriodMs = 50U;
constexpr UBaseType_t kSensorTaskPriority = configMAX_PRIORITIES - 3;
constexpr UBaseType_t kTelemetryTaskPriority = 2U;
constexpr BaseType_t kSensorTaskCore = 0;
constexpr BaseType_t kTelemetryTaskCore = 1;

#if defined(TRIWHIRL_ROUTE_B_SENSOR_COMMISSIONING_BT)
constexpr char kBluetoothDeviceName[] = "TriWhirl-Sensor";
constexpr char kBluetoothServiceName[] = "TriWhirl Sensor Telemetry";
constexpr EventBits_t kBluetoothReadyBit = BIT0;
constexpr EventBits_t kBluetoothFailedBit = BIT1;
EventGroupHandle_t bluetooth_event_group = nullptr;
std::atomic<std::uint32_t> bluetooth_spp_handle{0U};
std::atomic<bool> bluetooth_spp_congested{false};
std::atomic<bool> bluetooth_spp_tx_pending{false};
#endif

struct TimingStats {
  std::uint64_t count = 0U;
  std::uint64_t total_us = 0U;
  std::uint32_t min_us = std::numeric_limits<std::uint32_t>::max();
  std::uint32_t max_us = 0U;

  void record(const std::uint32_t value_us) {
    ++count;
    total_us += value_us;
    min_us = std::min(min_us, value_us);
    max_us = std::max(max_us, value_us);
  }

  double meanUs() const {
    return count == 0U ? 0.0 : static_cast<double>(total_us) /
                                  static_cast<double>(count);
  }

  std::uint32_t visibleMinUs() const {
    return count == 0U ? 0U : min_us;
  }
};

struct SensorCommissioningSnapshot {
  std::uint64_t timestamp_us = 0U;
  std::uint64_t sample_count = 0U;
  std::uint64_t invalid_samples = 0U;
  std::uint32_t service_us = 0U;
  std::uint32_t service_min_us = 0U;
  std::uint32_t service_max_us = 0U;
  double service_mean_us = 0.0;
  std::uint32_t period_us = 0U;
  std::uint32_t period_min_us = 0U;
  std::uint32_t period_max_us = 0U;
  double period_mean_us = 0.0;
  simplefoc::SimpleFocSensorObservation sensor{};
};

QueueHandle_t snapshot_queue = nullptr;

simplefoc::SimpleFocSensorConfig boardSensorConfig() {
  simplefoc::SimpleFocSensorConfig config{};
  config.i2c_bus_index = 0;
  config.sda_gpio = board::kAs5600SdaGpio;
  config.scl_gpio = board::kAs5600SclGpio;
  config.i2c_hz = kSensorBusHz;
  return config;
}

[[noreturn]] void fatalLoop(const char* const reason) {
  std::printf("FATAL sfoc_sensor reason=%s\r\n", reason);
  std::fflush(stdout);
  for (;;) {
    vTaskDelay(pdMS_TO_TICKS(1000));
  }
}

#if defined(TRIWHIRL_ROUTE_B_SENSOR_COMMISSIONING_BT)
void markBluetoothStartupFailed() {
  if (bluetooth_event_group != nullptr) {
    xEventGroupSetBits(bluetooth_event_group, kBluetoothFailedBit);
  }
}

void bluetoothGapCallback(const esp_bt_gap_cb_event_t event,
                          esp_bt_gap_cb_param_t* const param) {
  if (param == nullptr) {
    return;
  }

  switch (event) {
    case ESP_BT_GAP_CFM_REQ_EVT:
      // Headless commissioning device: advertise no I/O capability and accept
      // the Just Works confirmation generated by Secure Simple Pairing.
      (void)esp_bt_gap_ssp_confirm_reply(param->cfm_req.bda, true);
      break;
    case ESP_BT_GAP_PIN_REQ_EVT: {
      // Legacy fallback for hosts that do not negotiate SSP.
      esp_bt_pin_code_t pin_code{};
      pin_code[0] = '1';
      pin_code[1] = '2';
      pin_code[2] = '3';
      pin_code[3] = '4';
      (void)esp_bt_gap_pin_reply(param->pin_req.bda, true, 4U, pin_code);
      break;
    }
    default:
      break;
  }
}

void bluetoothSppCallback(const esp_spp_cb_event_t event,
                          esp_spp_cb_param_t* const param) {
  if (param == nullptr) {
    return;
  }

  switch (event) {
    case ESP_SPP_INIT_EVT:
      if (param->init.status != ESP_SPP_SUCCESS ||
          esp_spp_start_srv(ESP_SPP_SEC_AUTHENTICATE, ESP_SPP_ROLE_SLAVE, 0U,
                            kBluetoothServiceName) != ESP_OK) {
        markBluetoothStartupFailed();
      }
      break;

    case ESP_SPP_START_EVT:
      if (param->start.status != ESP_SPP_SUCCESS ||
          esp_bt_gap_set_device_name(kBluetoothDeviceName) != ESP_OK ||
          esp_bt_gap_set_scan_mode(ESP_BT_CONNECTABLE,
                                   ESP_BT_GENERAL_DISCOVERABLE) != ESP_OK) {
        markBluetoothStartupFailed();
        break;
      }
      if (bluetooth_event_group != nullptr) {
        xEventGroupSetBits(bluetooth_event_group, kBluetoothReadyBit);
      }
      break;

    case ESP_SPP_SRV_OPEN_EVT:
      if (param->srv_open.status == ESP_SPP_SUCCESS) {
        bluetooth_spp_handle.store(param->srv_open.handle,
                                   std::memory_order_relaxed);
        bluetooth_spp_congested.store(false, std::memory_order_relaxed);
        bluetooth_spp_tx_pending.store(false, std::memory_order_relaxed);
      }
      break;

    case ESP_SPP_CLOSE_EVT:
      if (bluetooth_spp_handle.load(std::memory_order_relaxed) ==
          param->close.handle) {
        bluetooth_spp_handle.store(0U, std::memory_order_relaxed);
        bluetooth_spp_congested.store(false, std::memory_order_relaxed);
        bluetooth_spp_tx_pending.store(false, std::memory_order_relaxed);
      }
      break;

    case ESP_SPP_CONG_EVT:
      if (bluetooth_spp_handle.load(std::memory_order_relaxed) ==
          param->cong.handle) {
        bluetooth_spp_congested.store(param->cong.cong,
                                      std::memory_order_relaxed);
      }
      break;

    case ESP_SPP_WRITE_EVT:
      bluetooth_spp_tx_pending.store(false, std::memory_order_relaxed);
      break;

    default:
      break;
  }
}

bool beginBluetoothSpp() {
  // Allocate all callback-visible state before esp_spp_enhanced_init(). This
  // ordering is deliberate: the pinned Arduino BluetoothSerial wrapper does
  // the inverse and can drop an immediate ESP_SPP_INIT_EVT, which caused the
  // observed five-second startup timeout on hardware.
  bluetooth_event_group = xEventGroupCreate();
  if (bluetooth_event_group == nullptr) {
    return false;
  }

  if (!btStarted() && !btStartMode(BT_MODE_CLASSIC_BT)) {
    return false;
  }

  esp_bluedroid_status_t bluedroid_status = esp_bluedroid_get_status();
  if (bluedroid_status == ESP_BLUEDROID_STATUS_UNINITIALIZED) {
    if (esp_bluedroid_init() != ESP_OK) {
      return false;
    }
    bluedroid_status = esp_bluedroid_get_status();
  }
  if (bluedroid_status != ESP_BLUEDROID_STATUS_ENABLED) {
    if (esp_bluedroid_enable() != ESP_OK) {
      return false;
    }
  }

  if (esp_bt_gap_register_callback(bluetoothGapCallback) != ESP_OK ||
      esp_spp_register_callback(bluetoothSppCallback) != ESP_OK) {
    return false;
  }

  esp_bt_sp_param_t param_type = ESP_BT_SP_IOCAP_MODE;
  esp_bt_io_cap_t iocap = ESP_BT_IO_CAP_NONE;
  if (esp_bt_gap_set_security_param(param_type, &iocap, sizeof(iocap)) !=
      ESP_OK) {
    return false;
  }

  esp_spp_cfg_t spp_config = BT_SPP_DEFAULT_CONFIG();
  spp_config.mode = ESP_SPP_MODE_CB;
  if (esp_spp_enhanced_init(&spp_config) != ESP_OK) {
    return false;
  }

  const EventBits_t bits = xEventGroupWaitBits(
      bluetooth_event_group, kBluetoothReadyBit | kBluetoothFailedBit, pdFALSE,
      pdFALSE, pdMS_TO_TICKS(5000));
  return (bits & kBluetoothReadyBit) != 0U &&
         (bits & kBluetoothFailedBit) == 0U;
}
#endif

void emitTelemetryLine(const char* const line, const std::size_t length) {
#if defined(TRIWHIRL_ROUTE_B_SENSOR_COMMISSIONING_BT)
  // Direct ESP-IDF SPP is commissioning transport only. Transmission stays in
  // this low-priority 20 Hz task. Drop a row rather than block if the peer is
  // absent, congested, or a prior asynchronous write is still outstanding.
  const std::uint32_t handle =
      bluetooth_spp_handle.load(std::memory_order_relaxed);
  if (handle == 0U ||
      bluetooth_spp_congested.load(std::memory_order_relaxed)) {
    return;
  }

  bool expected = false;
  if (!bluetooth_spp_tx_pending.compare_exchange_strong(
          expected, true, std::memory_order_relaxed)) {
    return;
  }

  const esp_err_t result = esp_spp_write(
      handle, static_cast<int>(length),
      reinterpret_cast<std::uint8_t*>(const_cast<char*>(line)));
  if (result != ESP_OK) {
    bluetooth_spp_tx_pending.store(false, std::memory_order_relaxed);
  }
#else
  (void)std::fwrite(line, 1U, length, stdout);
  std::fflush(stdout);
#endif
}

void sensorTask(void*) {
  const simplefoc::SimpleFocSensorConfig config = boardSensorConfig();
  if (!simplefoc::validSimpleFocSensorConfig(config)) {
    fatalLoop("invalid_config");
  }

  // This is the only sensor hardware object in the active commissioning path.
  // SimpleFocSensorPath contains TwoWire + MagneticSensorI2C only.
  simplefoc::SimpleFocSensorPath sensor(config);
  if (!sensor.begin()) {
    fatalLoop("sensor_begin_failed");
  }

  TimingStats service_timing{};
  TimingStats period_timing{};
  std::uint64_t invalid_samples = 0U;
  std::uint64_t previous_service_start_us = 0U;
  TickType_t last_wake = xTaskGetTickCount();

  for (;;) {
    const std::uint64_t service_start_us =
        static_cast<std::uint64_t>(esp_timer_get_time());
    std::uint32_t period_us = 0U;
    if (previous_service_start_us != 0U) {
      const std::uint64_t delta_us = service_start_us - previous_service_start_us;
      period_us = delta_us > std::numeric_limits<std::uint32_t>::max()
                      ? std::numeric_limits<std::uint32_t>::max()
                      : static_cast<std::uint32_t>(delta_us);
      period_timing.record(period_us);
    }
    previous_service_start_us = service_start_us;

    const bool sample_ok = sensor.service();
    const std::uint64_t service_end_us =
        static_cast<std::uint64_t>(esp_timer_get_time());
    const std::uint64_t elapsed_us = service_end_us - service_start_us;
    const std::uint32_t service_us =
        elapsed_us > std::numeric_limits<std::uint32_t>::max()
            ? std::numeric_limits<std::uint32_t>::max()
            : static_cast<std::uint32_t>(elapsed_us);
    service_timing.record(service_us);

    if (!sample_ok) {
      ++invalid_samples;
    }

    SensorCommissioningSnapshot snapshot{};
    snapshot.timestamp_us = service_end_us;
    snapshot.sample_count = service_timing.count;
    snapshot.invalid_samples = invalid_samples;
    snapshot.service_us = service_us;
    snapshot.service_min_us = service_timing.visibleMinUs();
    snapshot.service_max_us = service_timing.max_us;
    snapshot.service_mean_us = service_timing.meanUs();
    snapshot.period_us = period_us;
    snapshot.period_min_us = period_timing.visibleMinUs();
    snapshot.period_max_us = period_timing.max_us;
    snapshot.period_mean_us = period_timing.meanUs();
    snapshot.sensor = sensor.observation();
    (void)xQueueOverwrite(snapshot_queue, &snapshot);

    vTaskDelayUntil(&last_wake, pdMS_TO_TICKS(kServicePeriodMs));
  }
}

void telemetryTask(void*) {
  TickType_t last_wake = xTaskGetTickCount();
  for (;;) {
    vTaskDelayUntil(&last_wake, pdMS_TO_TICKS(kTelemetryPeriodMs));

    SensorCommissioningSnapshot snapshot{};
    if (xQueuePeek(snapshot_queue, &snapshot, 0) != pdTRUE) {
      continue;
    }

    char line[512]{};
    const int written = std::snprintf(
        line, sizeof(line),
        "sfoc_sensor,t_us=%" PRIu64
        ",sample=%" PRIu64
        ",valid=%u,wire_error=%u,angle_rad=%.6f,velocity_rad_s=%.6f"
        ",service_us=%" PRIu32
        ",service_min_us=%" PRIu32
        ",service_max_us=%" PRIu32
        ",service_mean_us=%.2f"
        ",period_us=%" PRIu32
        ",period_min_us=%" PRIu32
        ",period_max_us=%" PRIu32
        ",period_mean_us=%.2f"
        ",invalid_samples=%" PRIu64 "\r\n",
        snapshot.timestamp_us,
        snapshot.sample_count,
        snapshot.sensor.sample_valid ? 1U : 0U,
        static_cast<unsigned>(snapshot.sensor.wire_error),
        static_cast<double>(snapshot.sensor.shaft_angle_rad),
        static_cast<double>(snapshot.sensor.shaft_velocity_rad_s),
        snapshot.service_us,
        snapshot.service_min_us,
        snapshot.service_max_us,
        snapshot.service_mean_us,
        snapshot.period_us,
        snapshot.period_min_us,
        snapshot.period_max_us,
        snapshot.period_mean_us,
        snapshot.invalid_samples);
    if (written <= 0 || static_cast<std::size_t>(written) >= sizeof(line)) {
      continue;
    }
    emitTelemetryLine(line, static_cast<std::size_t>(written));
  }
}

}  // namespace

[[noreturn]] void runSimpleFocSensorCommissioning() {
  // TriWhirl supplies app_main in the dual-framework build, so initialize the
  // Arduino HAL explicitly before constructing the pinned TwoWire-based
  // SimpleFOC sensor path. CONFIG_AUTOSTART_ARDUINO is not relied upon here.
  initArduino();

#if defined(TRIWHIRL_ROUTE_B_SENSOR_COMMISSIONING_BT)
  if (!beginBluetoothSpp()) {
    std::printf("Bluetooth SPP direct init failed\r\n");
    std::fflush(stdout);
    fatalLoop("bluetooth_spp_begin_failed");
  }
  std::printf(
      "TriWhirl SimpleFOC sensor-only commissioning\r\n"
      "transport=bluetooth_spp_direct,name=%s,"
      "owner=SimpleFOC,actuator=DISABLED,motor_init=ABSENT\r\n",
      kBluetoothDeviceName);
#else
  std::printf(
      "TriWhirl SimpleFOC sensor-only commissioning\r\n"
      "transport=uart,owner=SimpleFOC,actuator=DISABLED,motor_init=ABSENT\r\n");
#endif

  const simplefoc::SimpleFocSensorConfig config = boardSensorConfig();
  std::printf(
      "sda=%d,scl=%d,i2c_hz=%" PRIu32 ",service_hz=1000,telemetry_hz=20\r\n",
      config.sda_gpio, config.scl_gpio, config.i2c_hz);
  std::fflush(stdout);

  snapshot_queue = xQueueCreate(1U, sizeof(SensorCommissioningSnapshot));
  if (snapshot_queue == nullptr) {
    fatalLoop("snapshot_queue_create_failed");
  }

  if (xTaskCreatePinnedToCore(telemetryTask, "sfoc_sensor_telemetry", 4096,
                              nullptr, kTelemetryTaskPriority, nullptr,
                              kTelemetryTaskCore) != pdPASS) {
    fatalLoop("telemetry_task_create_failed");
  }

  if (xTaskCreatePinnedToCore(sensorTask, "sfoc_sensor", 4096, nullptr,
                              kSensorTaskPriority, nullptr,
                              kSensorTaskCore) != pdPASS) {
    fatalLoop("sensor_task_create_failed");
  }

  vTaskDelete(nullptr);
  for (;;) {
  }
}

}  // namespace triwhirl::runtime

#endif  // TRIWHIRL_ROUTE_B_SENSOR_COMMISSIONING && backend
