#!/usr/bin/env python3
"""Synthesize one common continuous-time H-infinity state-feedback gain.

Input is the empirical polytopic model generated by
model/uncertainty/build_polytopic.py.  The same X/Y decision variables are used
for every plant vertex, giving a common-Lyapunov robust state-feedback law.

Project convention:
    Vq = -K_inf x

The LMI is solved in variables X > 0 and Y = F X, where u = F x; therefore
K_inf = -Y X^{-1}.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Synthesize a common robust H-infinity gain for all plant vertices."
    )
    parser.add_argument("input", type=Path, help="polytopic uncertainty JSON")
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--theta-scale-deg", type=float, default=8.0)
    parser.add_argument("--rate-scale", type=float, default=10.0)
    parser.add_argument("--wheel-scale", type=float, default=40.0)
    parser.add_argument("--vq-scale", type=float, default=1.2)
    parser.add_argument("--eps", type=float, default=1.0e-7)
    parser.add_argument(
        "--solver",
        default="CLARABEL",
        help="cvxpy solver name; try CLARABEL, CVXOPT, MOSEK, or SCS",
    )
    return parser.parse_args()


def eig_json(matrix: np.ndarray) -> list[dict[str, float]]:
    return [
        {"real": float(value.real), "imag": float(value.imag)}
        for value in np.linalg.eigvals(matrix)
    ]


def main() -> int:
    args = parse_args()
    try:
        import cvxpy as cp
    except ImportError as exc:
        raise RuntimeError(
            "cvxpy is required for H-infinity synthesis; install it in the host venv"
        ) from exc

    if (
        args.theta_scale_deg <= 0.0
        or args.rate_scale <= 0.0
        or args.wheel_scale <= 0.0
        or args.vq_scale <= 0.0
        or args.eps <= 0.0
    ):
        raise RuntimeError("all scales and --eps must be positive")

    payload = json.loads(args.input.read_text(encoding="utf-8"))
    poly = payload.get("polytope", {})
    vertices = poly.get("vertices", []) if isinstance(poly, dict) else []
    if not isinstance(vertices, list) or not vertices:
        raise RuntimeError("input contains no polytopic plant vertices")

    plants: list[tuple[str, np.ndarray, np.ndarray]] = []
    for item in vertices:
        a = np.asarray(item["A"], dtype=float)
        b = np.asarray(item["Bv"], dtype=float)
        if a.shape != (3, 3) or b.shape != (3, 1):
            raise RuntimeError("expected A=3x3 and Bv=3x1")
        plants.append((str(item.get("id", "plant")), a, b))

    theta_scale = math.radians(args.theta_scale_deg)
    c_state = np.diag(
        [1.0 / theta_scale, 1.0 / args.rate_scale, 1.0 / args.wheel_scale]
    )
    # z = [normalized theta, normalized body rate, normalized wheel rate,
    #      normalized control effort]
    cz = np.vstack((c_state, np.zeros((1, 3))))
    dzu = np.asarray([[0.0], [0.0], [0.0], [1.0 / args.vq_scale]])
    # Disturbance channels represent additive unmodeled body and wheel angular
    # acceleration.  Their units remain rad/s^2; gamma is meaningful only with
    # this disturbance convention documented alongside the state/output scales.
    bw = np.asarray([[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]])

    n = 3
    nw = bw.shape[1]
    nz = cz.shape[0]
    x = cp.Variable((n, n), symmetric=True)
    y = cp.Variable((1, n))
    gamma = cp.Variable(nonneg=True)
    constraints = [x >> args.eps * np.eye(n), gamma >= args.eps]

    for _name, a, b in plants:
        axby = a @ x + b @ y
        zxy = cz @ x + dzu @ y
        lmi = cp.bmat(
            [
                [axby + axby.T, bw, zxy.T],
                [bw.T, -gamma * np.eye(nw), np.zeros((nw, nz))],
                [zxy, np.zeros((nz, nw)), -gamma * np.eye(nz)],
            ]
        )
        constraints.append(lmi << -args.eps * np.eye(n + nw + nz))

    problem = cp.Problem(cp.Minimize(gamma), constraints)
    try:
        problem.solve(solver=args.solver)
    except Exception as exc:
        raise RuntimeError(f"cvxpy solver {args.solver} failed: {exc}") from exc

    if problem.status not in {cp.OPTIMAL, cp.OPTIMAL_INACCURATE}:
        raise RuntimeError(f"H-infinity synthesis did not converge: status={problem.status}")
    if x.value is None or y.value is None or gamma.value is None:
        raise RuntimeError("solver returned no decision-variable values")

    x_value = np.asarray(x.value, dtype=float)
    y_value = np.asarray(y.value, dtype=float)
    f_gain = y_value @ np.linalg.inv(x_value)
    k_inf = -f_gain

    checks: list[dict[str, object]] = []
    all_stable = True
    for name, a, b in plants:
        acl = a - b @ k_inf
        eig = np.linalg.eigvals(acl)
        stable = bool(np.all(np.real(eig) < 0.0))
        all_stable = all_stable and stable
        checks.append(
            {
                "plant": name,
                "stable": stable,
                "closed_loop_eigenvalues": [
                    {"real": float(value.real), "imag": float(value.imag)} for value in eig
                ],
            }
        )

    result = {
        "format": "triwhirl-hinf-state-feedback-v1",
        "source_polytope": str(args.input),
        "solver": args.solver,
        "solver_status": problem.status,
        "gamma": float(gamma.value),
        "control_law": "Vq = -K_inf * [theta_error, theta_rate, wheel_rate]^T",
        "K_inf": k_inf.reshape(-1).tolist(),
        "decision_X": x_value.tolist(),
        "decision_Y": y_value.tolist(),
        "performance_scales": {
            "theta_error_deg": args.theta_scale_deg,
            "theta_rate_rad_s": args.rate_scale,
            "wheel_rate_rad_s": args.wheel_scale,
            "Vq_v": args.vq_scale,
        },
        "disturbance_channels": {
            "Bw": bw.tolist(),
            "meaning": ["additive body angular acceleration", "additive wheel angular acceleration"],
        },
        "plant_checks": checks,
        "all_vertices_stable": all_stable,
        "note": (
            "This is an offline common-Lyapunov continuous-time synthesis result. "
            "Do not deploy until timing/sample-rate handling, saturation, wheel-speed limits, "
            "and hardware closed-loop bring-up requirements are satisfied."
        ),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(args.output)
    print(f"status={problem.status} gamma={float(gamma.value):.6g}")
    print("K_inf=" + " ".join(f"{value:.9g}" for value in k_inf.reshape(-1)))
    print("all plant vertices stable=" + str(all_stable).lower())
    return 0 if all_stable else 2


if __name__ == "__main__":
    raise SystemExit(main())
