#!/usr/bin/env python3
"""Serve the TriWhirl simulation console and fresh native SITL evidence over SSE.

The browser remains display/control surface only. Every run is generated by the
native C++ SITL that compiles the production StandupController. Disturbance
button presses are handled by deterministic rewind/recompute: the browser sends
all disturbance events accumulated so far, the backend reruns the native model
from t=0 with those impulses, and streaming resumes at the click time. This keeps
controller/plant dynamics out of Python while still allowing interactive pushes.
"""

from __future__ import annotations

import argparse
import csv
import errno
import json
import math
import os
import subprocess
import tempfile
import time
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]

CLIENT_DISCONNECT_ERRORS = (
    BrokenPipeError,
    ConnectionResetError,
    ConnectionAbortedError,
)
CLIENT_DISCONNECT_ERRNOS = {errno.EPIPE, errno.ECONNRESET, errno.ECONNABORTED}
CLIENT_DISCONNECT_WINERRORS = {10053, 10054, 10058}

NUMERIC_FIELDS = {
    "t_s",
    "true_error_rad",
    "true_error_deg",
    "true_theta_rate_rad_s",
    "true_wheel_rate_rad_s",
    "true_wheel_angle_rad",
    "filtered_rate_rad_s",
    "target_velocity_rad_s",
    "velocity_error_rad_s",
    "velocity_integral_v",
    "vq_unclamped_v",
    "vq_target_v",
    "vq_applied_v",
}
BOOL_FIELDS = {"settling", "stable", "target_saturated", "vq_saturated"}


def is_client_disconnect(error: BaseException) -> bool:
    if isinstance(error, CLIENT_DISCONNECT_ERRORS):
        return True
    if isinstance(error, OSError):
        if error.errno in CLIENT_DISCONNECT_ERRNOS:
            return True
        if getattr(error, "winerror", None) in CLIENT_DISCONNECT_WINERRORS:
            return True
    return False


def sse_payload(event: str, payload: object) -> bytes:
    data = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    return f"event: {event}\ndata: {data}\n\n".encode("utf-8")


def executable_candidates(name: str) -> list[Path]:
    exe = f"{name}.exe" if os.name == "nt" else name
    return [
        ROOT / "build" / "sitl" / "Release" / exe,
        ROOT / "build" / "sitl" / "Debug" / exe,
        ROOT / "build" / "sitl" / exe,
    ]


def resolve_executable(explicit: str | None, name: str) -> Path:
    if explicit:
        candidate = Path(explicit).expanduser().resolve()
        if candidate.is_file():
            return candidate
        raise FileNotFoundError(f"SITL executable not found: {candidate}")
    for candidate in executable_candidates(name):
        if candidate.is_file():
            return candidate
    searched = "\n  ".join(str(path) for path in executable_candidates(name))
    raise FileNotFoundError(
        f"{name} executable not found. Build it first. Searched:\n  {searched}"
    )


def parse_row(row: dict[str, str]) -> dict[str, object]:
    sample: dict[str, object] = {}
    for key, value in row.items():
        if key in NUMERIC_FIELDS:
            sample[key] = float(value)
        elif key in BOOL_FIELDS:
            sample[key] = value == "1"
        else:
            sample[key] = value
    return sample


def parse_disturbance_specs(
    values: list[str], *, kind: str, magnitude_limit: float
) -> list[dict[str, object]]:
    events: list[dict[str, object]] = []
    for raw in values:
        try:
            time_text, delta_text = raw.split(":", 1)
            t_s = float(time_text)
            delta = float(delta_text)
        except (ValueError, TypeError) as error:
            raise ValueError(
                f"{kind} disturbance must use time_s:delta_rad_s, got {raw!r}"
            ) from error
        if not math.isfinite(t_s) or not math.isfinite(delta):
            raise ValueError(f"{kind} disturbance must be finite")
        if not (0.0 <= t_s <= 10.0):
            raise ValueError(f"{kind} disturbance time must be in [0, 10] s")
        if abs(delta) > magnitude_limit:
            raise ValueError(
                f"{kind} disturbance magnitude exceeds {magnitude_limit} rad/s"
            )
        events.append({"kind": kind, "t_s": t_s, "delta_rad_s": delta})
    return events


def run_fresh_simulation(
    base_executable: Path,
    disturbance_executable: Path,
    profile: str,
    disturbances: list[dict[str, object]],
) -> tuple[list[dict[str, object]], bool, str, str]:
    temp = tempfile.NamedTemporaryFile(prefix="triwhirl-sitl-", suffix=".csv", delete=False)
    temp_path = Path(temp.name)
    temp.close()
    try:
        disturbed = bool(disturbances)
        executable = disturbance_executable if disturbed else base_executable
        command = [
            str(executable),
            "--scenario",
            "balance-demo",
            "--profile",
            profile,
            "--duration-ms",
            "10000",
            "--output",
            str(temp_path),
        ]
        if disturbed:
            for event in disturbances:
                option = "--body-kick" if event["kind"] == "body" else "--wheel-kick"
                command.extend(
                    [
                        option,
                        f'{float(event["t_s"]):.6f}:{float(event["delta_rad_s"]):.6f}',
                    ]
                )
            command.append("--require-disturbance-gate")
            gate_token = "disturbance_gate=PASS"
            gate_name = "DISTURBANCE"
        else:
            command.append("--require-balance-gate")
            gate_token = "balance_gate=PASS"
            gate_name = "BALANCE"

        completed = subprocess.run(
            command,
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
            timeout=30.0,
        )
        stdout = completed.stdout.strip()
        stderr = completed.stderr.strip()
        if completed.returncode not in (0, 1):
            raise RuntimeError(stderr or stdout or f"native SITL exited with {completed.returncode}")
        if not temp_path.is_file() or temp_path.stat().st_size == 0:
            raise RuntimeError(stderr or stdout or "native SITL produced no evidence CSV")
        with temp_path.open(newline="", encoding="utf-8") as stream:
            samples = [parse_row(row) for row in csv.DictReader(stream)]
        if not samples:
            raise RuntimeError("native SITL evidence CSV contained no samples")
        gate_pass = completed.returncode == 0 and gate_token in stdout
        summary = stdout.splitlines()[-1] if stdout else (stderr or "native SITL finished")
        return samples, gate_pass, summary, gate_name
    finally:
        try:
            temp_path.unlink()
        except FileNotFoundError:
            pass


class Handler(SimpleHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    sitl_executable: Path
    disturbance_executable: Path

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def log_message(self, fmt: str, *args) -> None:
        print(f"[{self.log_date_time_string()}] {fmt % args}")

    def handle(self) -> None:
        try:
            super().handle()
        except OSError as error:
            if not is_client_disconnect(error):
                raise

    def finish(self) -> None:
        try:
            super().finish()
        except OSError as error:
            if not is_client_disconnect(error):
                raise

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/api/health":
            body = json.dumps(
                {
                    "ok": True,
                    "service": "triwhirl-sim-viewer",
                    "sitl": str(self.sitl_executable),
                    "disturbance_sitl": str(self.disturbance_executable),
                }
            ).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        if parsed.path == "/api/live":
            self.stream_live(parsed.query)
            return
        super().do_GET()

    def write_sse(self, event: str, payload: object) -> bool:
        try:
            self.wfile.write(sse_payload(event, payload))
            self.wfile.flush()
            return True
        except OSError as error:
            if is_client_disconnect(error):
                return False
            raise

    def stream_live(self, query: str) -> None:
        params = parse_qs(query)
        profile = params.get("profile", ["nominal"])[0]
        if profile not in {"nominal", "B", "C"}:
            self.send_error(400, "profile must be nominal, B, or C")
            return
        try:
            speed = float(params.get("speed", ["1"])[0])
            fps = float(params.get("fps", ["60"])[0])
            resume_from = float(params.get("resume_from", ["0"])[0])
            body = parse_disturbance_specs(
                params.get("body_kick", []), kind="body", magnitude_limit=5.0
            )
            wheel = parse_disturbance_specs(
                params.get("wheel_kick", []), kind="wheel", magnitude_limit=100.0
            )
            disturbances = sorted(body + wheel, key=lambda item: float(item["t_s"]))
        except ValueError as error:
            self.send_error(400, str(error))
            return
        if not math.isfinite(speed) or not (0.1 <= speed <= 10.0):
            self.send_error(400, "speed must be in [0.1, 10]")
            return
        if not math.isfinite(fps) or not (5.0 <= fps <= 120.0):
            self.send_error(400, "fps must be in [5, 120]")
            return
        if not math.isfinite(resume_from) or not (0.0 <= resume_from <= 10.0):
            self.send_error(400, "resume_from must be in [0, 10]")
            return

        try:
            samples, gate_pass, summary, gate_name = run_fresh_simulation(
                self.sitl_executable,
                self.disturbance_executable,
                profile,
                disturbances,
            )
        except Exception as error:  # noqa: BLE001 - surface backend failure.
            body_text = str(error).encode("utf-8")
            self.send_response(500)
            self.send_header("Content-Type", "text/plain; charset=utf-8")
            self.send_header("Content-Length", str(len(body_text)))
            self.end_headers()
            self.wfile.write(body_text)
            return

        self.close_connection = True
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "close")
        self.send_header("X-Accel-Buffering", "no")
        self.end_headers()

        try:
            if not self.write_sse(
                "meta",
                {
                    "schema": 2,
                    "source": "fresh native C++ SITL",
                    "profile": profile,
                    "gate": gate_name,
                    "gate_pass": gate_pass,
                    "duration_s": float(samples[-1]["t_s"]),
                    "display_fps_limit": fps,
                    "speed": speed,
                    "resume_from_s": resume_from,
                    "disturbances": disturbances,
                    "scope": (
                        "Production StandupController + provisional local plant; "
                        "disturbances are native-SITL impulses via deterministic "
                        "rewind/recompute; simulation evidence only."
                    ),
                },
            ):
                return

            display_period = 1.0 / fps
            next_display_t = resume_from
            wall_anchor = time.perf_counter()
            for sample in samples:
                sim_t = float(sample["t_s"])
                if sim_t + 1.0e-12 < resume_from:
                    continue
                is_last = sample is samples[-1]
                if not is_last and sim_t + 1.0e-12 < next_display_t:
                    continue
                due = wall_anchor + max(0.0, sim_t - resume_from) / speed
                delay = due - time.perf_counter()
                if delay > 0:
                    time.sleep(delay)
                if not self.write_sse("sample", sample):
                    return
                while next_display_t <= sim_t + 1.0e-12:
                    next_display_t += display_period

            self.write_sse(
                "end",
                {
                    "gate": gate_name,
                    "gate_pass": gate_pass,
                    "summary": summary,
                    "t_s": samples[-1]["t_s"],
                    "disturbances": disturbances,
                },
            )
        except OSError as error:
            if not is_client_disconnect(error):
                raise
        except Exception as error:  # noqa: BLE001
            try:
                self.write_sse("stream-error", {"message": str(error)})
            except OSError as nested:
                if not is_client_disconnect(nested):
                    raise


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--exe", help="explicit native triwhirl-standup-sitl path")
    parser.add_argument(
        "--disturbance-exe",
        help="explicit native triwhirl-standup-sitl-disturbance path",
    )
    args = parser.parse_args()

    executable = resolve_executable(args.exe, "triwhirl-standup-sitl")
    disturbance_executable = resolve_executable(
        args.disturbance_exe, "triwhirl-standup-sitl-disturbance"
    )
    Handler.sitl_executable = executable
    Handler.disturbance_executable = disturbance_executable
    server = ThreadingHTTPServer((args.host, args.port), Handler)
    viewer = f"http://{args.host}:{args.port}/tools/visualization/triwhirl-sim-viewer/"
    print("TriWhirl Simulation Console")
    print(f"SITL:             {executable}")
    print(f"Disturbance SITL: {disturbance_executable}")
    print(f"viewer:           {viewer}")
    print("Ctrl+C to stop")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nKeyboard interrupt received, exiting.")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
